### ISSUE TITLE
Initial Pairing

### ISSUE THREAD

**Issue by Linkmonster666** [xerpi/ds3vita#7]
Has not connected once. I'm running Enso and I got the latest revision of the skprx. I'm using SD2vita with my my vita card as uma0 and my SD2vita as my ux0. I tried running it from the ur0:tai/config and from a ux0:tai/config. Added line ur0:tai/ds3vita.skprx under kernal. Also tried with a ux0 link.My mac ends in xx:52 so on the sixaxis pair tool I put in xx:53. Also my controller is (CECHZC2U A1) if that matters? I've tried everything I can think of. Any help or advise would be appreciated.

**Comment by Dimensional** [comment]
Unplug your controller from the PC after you've set up the mac. Reboot the Vita again, as sometimes this tends to help, and then make sure bluetooth is enabled. After that, press the PS button on the controller, and it should connect. Similar problem happened to me.

**Comment by Linkmonster666** [comment]
Turned out I had a controller that was too new. I bought an orginal
six-axis and a non rumble one and both work. Only issue I'm having now is
the L2, R2, L3 and R3 not working in remote play. lol

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
